export const dummyFreelanceDetail = (userId: string) => {
  switch (userId) {
    case "1":
      return {
        id: 1,
        imageUrl:
          "https://res.cloudinary.com/gurucom/image/upload/f_auto,w_128,h_128,dpr_2/pimg/1/891/1891022/photo_636001735363451538_guruImgLarge_1839478a-46a7-4e7d-b510-fd222d9979f0.jpg",
        address: "Gurgaon, Haryana, India",
        payYear: "30,236",
        name: "Anu Mittal",
        allTimeEarnings: "66K",
        transactionCompleted: "381",
        employers: "23",
        largestEmployers: "23K",
        memberSince: "May 2016",
        descriptionProfile:
          "For the last 17 years, Taskroots has been driven by customer satisfaction, with an average retention rate of six years. We thrive on delivering exemplary experience and tremendous value to our",
        typeService:
          "Administrative & Secretarial  >  Personal / Virtual Assistance",
        titleService: "Back Office Ops - Virtual Assistants",
        payService: "$10/hr · Starting at $25",
        descriptionService:
          "Our Virtual Assistants take pride in three core values - professionalism, proactivity and delivery within TAT. Our range of services include (but are not limited to): - Executive Virtual Assistant/Admin - Process Automation Management - Business Communication (Internal & External) - MIS - Customer Helpdesk - Calendar and Email Management - Team Management - MS Office/ File Management - Ecommerce Management",
        tagSkills: [
          "Administrative Assistant",
          "Calendar Management",
          "Correspondence Management",
          "Customer Service",
          "Email Services",
          "Executive Assistant",
          "File Management",
          "Help Desk",
          "Management",
          "Microsoft",
          "Multitasking",
          "Office Assistant",
          "Office Management",
          "Professional Organizer",
          "Time Management",
          "Virtual Assistants",
        ],
      };
    case "2":
      return {
        id: 2,
        imageUrl:
          "/images/20170805_093502_636375411570945345_guruImgLarge_2ebdefde-bbe7-46c8-8a43-de8febdc8532.avif",
        address: "Chelsea, OK, USA",
        payYear: "Past Earnings",
        name: "Ashley Boswell",
        allTimeEarnings: "189",
        transactionCompleted: "1",
        employers: "189",
        largestEmployers: "23K",
        memberSince: "Aug 2009",
        typeService: "Administrative & Secretarial",
        titleService: "Data Entry",
        payService: "$5/hr · Starting at $25",
        descriptionService:
          "With over 10 years of experience in administrative roles, including the medical profession I have the ability to accomplish any task no matter how big or small. I have an outstanding ability to communicate with all types of people on a personal level which in turn gets the job done correctly in a timely manner.",
        tagSkills: ["Medical", "Microsoft"],
      };
    case "3":
      return {
        id: 3,
        imageUrl:
          "/images/Arun_637227661339530961_guruImgLarge_3429529e-2cf6-46e8-b66a-245421803c8e.avif",
        address: "Mumbai, Maharashtra, India",
        payYear: "Past Earnings",
        name: "Arun Kumar (Certified GTD Trainer)",
        allTimeEarnings: "100",
        transactionCompleted: "1",
        employers: "1",
        largestEmployers: "100",
        memberSince: "Feb 2011",
        descriptionProfile:
          "I am best at consulting, project management, and growth hacking. My expertise is in teaching, training and entrepreneurship. I wrote 2 book on Ecommerce & entrepreneurship mgmt. I also teach at few ",
        typeService: "Business & Finance  >  Business Management & Consulting",
        titleService: "Business Consulting",
        payService: "$35/hr · Starting at $35",
        descriptionService:
          "Plan, organize and manage business projects for clients Perform initial assessments for each client before the project begins Constantly recommend solutions for improvement Develop detailed business plans Determine the project's KPIs Track KPIs and prepare reports 10 years of experience as the business consultant Knowledge of diverse business areas and fields such as IT, Marketing, HR etc. Familiarity with business management software such as CRM and ERP Analyze and interpret data to unearth weaknesses and problems, and comprehend the causes",
        tagSkills: [
          "Business Analysis",
          "Business Communications",
          "Business Consultant",
          "Business Consulting",
          "Business Development",
          "Business Management",
          "Business Planning",
          "Business",
          "Process Management",
          "Business Services",
          "Business Strategy",
          "Business Training",
          "Consultant",
          "Corporate Training",
          "E Commerce",
          "Motivational Speaking",
          "Product Management",
          "Program Management",
          "Project Management",
          "Startup Consulting",
        ],
      };
    case "4":
      return {
        id: 4,
        imageUrl:
          "https://res.cloudinary.com/gurucom/image/upload/f_auto,w_128,h_128,dpr_2/v1679495317/pimg/FreelancerFiles/4/745/4745079/etezjdinjepkxqwpurpt.jpg",
        address: "Havant, England, United Kingdom",
        payYear: "1,768",
        name: "Martin Jackson",
        allTimeEarnings: "1,768",
        transactionCompleted: "4",
        employers: "1",
        largestEmployers: "1,768",
        memberSince: "Mar 2023",
        descriptionProfile:
          "About Me: I'm a dedicated and forward-thinking management consultant with a passion for helping businesses achieve their strategic objectives and unlock their full potential. With extensive",
        typeService: "Business & Finance  >  Business Management & Consulting",
        titleService: "Business & Management Consulting",
        payService: "$95/hr · Starting at $75",
        descriptionService:
          "My management consulting services focus on your most critical issues and opportunities: strategy, marketing, organization, operations, technology, transformation, digital, advanced analytics, corporate finance, mergers & acquisitions and sustainability across all industries and geographies. I bring deep, functional expertise, but am known for a holistic perspective: I capture value across boundaries and between the silos of any organization. I have proven a multiplier effect from optimizing the sum of the parts, not just the individual pieces.",
        tagSkills: [
          "Business Analysis",
          "Business Consulting",
          "Business Development",
          "Business Management",
          "Business Process Management",
          "Business Strategy",
          "Business Training",
          "Business Valuation",
          "Compliance Consulting",
          "Consultant",
          "Contract Management",
          "Corporate Governance",
          "Crisis Management",
          "E Commerce",
          "Management",
          "Management Consulting",
          "Operations Management",
          "Program Management",
          "Project Management",
          "Startup Consulting",
          "Supply Chain Management",
          "Workflow Management",
        ],
      };
    case "5":
      return {
        id: 5,
        imageUrl: "/images/pzxb4pejakj8u0rwywe7.avif",
        address: "Mexico, Nuevo Leon, Mexico",
        name: "Yvone Castillo",
        allTimeEarnings: "21K",
        transactionCompleted: "52",
        employers: "7",
        largestEmployers: "10",
        memberSince: "Aug 2022",
        descriptionProfile:
          "Hi! I'm an industrial designer with extensive experience on interior design, architectural visualization, 3D modeling and rendering. With more than 5 years of experience in architectural 3D",
        typeService:
          "Design & Art  >  Interiors / Exteriors / Furniture / Landscapes",
        titleService: "Interior design and rendering",
        payService: "$20/hr · Starting at $100",
        descriptionService:
          "Hi! I'm an industrial designer with a broad experience on interior design and architecture visualization. For the past few years I've worked on several interior design projects, creating the full concept design of residential and commercial sectors. I use different 3D modeling software like: Blender, sketchup, 3D Max. In this service I'm offering the full design concept for your home or commercial space. What this includes is the following: 3D model of space (with design) Modern, creative and innovative interior design Functional space design to make sure that the space is well adapted and used. Photo-realistic renderings If needed a list of furniture / products used in the design so you can have the full information of where to buy.",
        tagSkills: [
          "3D Design",
          "3D Modeling",
          "3D Rendering",
          "3ds Max",
          "Decorating",
          "Furniture Design",
          "Home Design",
          "Industrial Design",
          "Interior Design",
          "Landscape Design",
          "Modeling",
          "Restaurant Design",
        ],
      };
    case "6":
      return {
        id: 6,
        imageUrl:
          "https://res.cloudinary.com/gurucom/image/upload/f_auto,w_128,h_128,dpr_2/pimg/2/184/2184858/PHOTO%20ALI_ABIDI_636358240520549748_guruImgLarge_961dcf55-1fa2-4a52-8007-108e04a90c3c.jpg",
        address: "Bou-Salem, Jendouba, Tunisia",
        name: "ALI ABIDI",
        payYear: "2,962",
        allTimeEarnings: "34K",
        transactionCompleted: "239",
        employers: "78",
        largestEmployers: "2,287",
        memberSince: "Jul 2017",
        descriptionProfile:
          "ALI ABIDI, graduated from University of Architecture & Urban Planning of Tunis. He had the chance to work in University of Tolima, Colombia as an intern. With artistic sensibility, great concern to ",
        typeService:
          "Design & Art  >  Interiors / Exteriors / Furniture / Landscapes",
        titleService: "Interior design and rendering",
        payService: "$20/hr · Starting at $100",
        descriptionService:
          "EUEXIA ARCHITECTURE is a multidisciplinary architecture firm founded in 2018 by ALI ABIDI, Architect who has chosen to put all his accumulated knowledge of different experiences all over the world, in the development of theoric approaches, architectural concepts and solutions. ALI is leading actually several categories of projects with different scales, such as, residential, commercial, office and interior design. With his ameobic team, Ali participates also in international competitions and had succeed before to win honourable prizes. Services and Intervention area is a worldwide, actually answering to different projects for clients in GURU, and collaborating also with international structures, mainly on: Residential Projects and Villas Interior Design mainly in USA and Middle East Showrooms and Retail Interior design Valorizing sustainable materials like CEB in Africa (Tunisia, Ghana and Senegal) Urban Planning and Landscaping",
        tagSkills: [
          "3D Interior Design",
          "Architects",
          "Architectural Design",
          "Architectural Modeling",
          "Building Information Modeling (BIM)",
          "Commercial Interior Design",
          "Concept Development",
          "Construction",
          "Construction Residential",
          "Design Floor Plan",
          "Hotel Design",
          "Interior Design",
          "Kitchen Design",
          "Landscape Design",
          "Lighting Design",
          "Residential Interior Design",
          "Restaurant Design",
          "Space Planning",
          "Sustainable Design",
          "Urban Planning",
        ],
      };
    case "7":
      return {
        id: 7,
        imageUrl:
          "https://res.cloudinary.com/gurucom/image/upload/f_auto,w_128,h_128,dpr_2/pimg/3/564/3564755/fullsizeoutput_677_637407362734441747_guruImgExtraLarge7220878c-e48f-45df-83c5-32b306895068.jpeg",
        address: "Carson, CA, USA",
        name: "Nicole Lunan",
        payYear: "134,320",
        allTimeEarnings: "344K",
        transactionCompleted: "73",
        employers: "1",
        largestEmployers: "344K",
        memberSince: "Nov 2020",
        typeService: "Sales & Marketing",
        titleService: "Marketing Specialist",
        payService: "$50/hr · Starting at $1K",
        descriptionService:
          "As a marketing specialist, Nicole Lunan assists in developing and executing campaigns to gain prospective customers and increase sales. She is also responsible for the following:  Manage the company websites and social media accounts Ensure consistent branding across digital and traditional channels  Work closely with the sales team to develop effective campaigns  Lead generation  Competitive analysis",
        tagSkills: [
          "Accounting",
          "Customer Service",
          "Lead Generation",
          "Marketing",
          "Sales",
          "Software Development",
          "Web Development",
        ],
      };
    case "8":
      return {
        id: 8,
        imageUrl: "/images/b7qjyajgsx8qxb89pt1h.avif",
        address: "newport coast, CA, USA",
        name: "Josclyn Virrey",
        payYear: "20,600",
        allTimeEarnings: "20K",
        transactionCompleted: "36",
        employers: "1",
        largestEmployers: "20K",
        memberSince: "May 2023",
        typeService: "Sales & Marketing  >  affiliate & referral programs",
        titleService: "Marketing and Sales Specialist",
        payService: "$44/hr · Starting at $25",
        descriptionService:
          "I am an experienced affiliate marketer. I am looking for part-time employment. I am a student in college. I am majoring in business. I specialize in Marketing and sales. I have previous on-site and in-building experience with affiliate marketing. With my view and my abilities to utilize modern technology to stay up to date with everything needed by young people for young people. I have many ways to add and suggest adjustments to modify your current business to help make them more appealing to a broader audience. ",
        tagSkills: [
          "Affiliate Marketing",
          "Business Proposal Writing",
          "Communication Development",
          "Information Technology",
          "Knowledge Process Outsourcing (KPO)",
          "Sales and Marketing",
        ],
      };
    case "9":
      return {
        id: 9,
        imageUrl:
          "https://res.cloudinary.com/gurucom/image/upload/f_auto,w_128,h_128,dpr_2/v1641725175/pimg/FreelancerFiles/4/094/4094905/v4thah8g6nymt8adedcu.jpg",
        address: "Dhule, Maharashtra, India",
        name: "Aishwarya Shinde 1",
        payYear: "17,050",
        allTimeEarnings: "19K",
        transactionCompleted: "55",
        employers: "1",
        largestEmployers: "19K",
        memberSince: "Jan 2022",
        typeService: "Sales & Marketing  Web / Digital Marketing",
        titleService: "Social Media Marketing",
        payService: "$25/hr · Starting at $50",
        descriptionService:
          "Hello, I'm here to help you manage, optimize, and grow your social media presence! Social media is more than just a trend. It is an essential piece of your business marketing strategy.",
        tagSkills: [
          "Content Marketing",
          "Digital Marketing",
          "Facebook Advertising",
          "Google Ads",
          "Google Certified",
          "Instagram Marketing",
          "Keyword Research",
          "LinkedIn Marketing",
          "Marketing",
          "Pinterest",
          "Search Engine Optimization (SEO)",
          "Social Media Marketing",
          "Twitter",
        ],
      };
    case "10":
      return {
        id: 10,
        imageUrl:
          "/images/headshotlulu_635338001201004201_guruImgLarge_dd61030f-d940-43be-870e-e3c1366c52f1.avif",
        address: "katy, TX, USA",
        name: "Leo Valk",
        allTimeEarnings: "76K",
        transactionCompleted: "9",
        employers: "8",
        largestEmployers: "19K",
        memberSince: "Apr 2014",
        typeService: "Business & Finance",
        titleService: "Human Resources / Management consultant",
        payService: "$50/hr · Starting at $25",
        descriptionService:
          "I provide Human Resources expertise and Management Consulting. Extensive experience in all aspects of HR and Compensation and Benefits, both in Europe and in the US. Developed also an expertise in social media and wordpress to support organizations.",
        tagSkills: [
          "Benefits",
          "Compensation Management",
          "Consultant",
          "Consulting",
          "Human Resources Consulting (HR)",
          "Human Resources Management (HR)",
          "Management",
          "Management Consulting",
          "WordPress",
        ],
      };
    case "11":
      return {
        id: 11,
        imageUrl: "/images/xejsruhf95ekwv1cmlib.avif",
        address: "Lahore, Punjab, Pakistan",
        name: "M. Azam Khan",
        allTimeEarnings: "567",
        transactionCompleted: "6",
        employers: "4",
        largestEmployers: "29",
        memberSince: "Sep 2018",
        typeService: "Business & Finance >  Human Resources (HR)",
        titleService: "Recruiting, IT Recruiter and Headhunter",
        payService: "$8/hr · Starting at $50",
        descriptionService:
          "I am an expert full-cycle recruiter and human resources administrator. I can work on your open positions, both IT and Non-IT roles. I have 8 years of experience working mainly in the IT industry.",
        tagSkills: [
          "GitHub",
          "Human Resources Management",
          "Information Technology",
          "Interviewing",
          "IT Recruitment",
          "Job Description Writing",
          "LinkedIn",
          "Onboarding",
          "Skype",
          "Staffing and Recruiting",
          "Talent Management",
          "Workforce Management",
        ],
      };
    case "12":
      return {
        id: 12,
        imageUrl: "/images/ob29qrbp3sx8zkhquwpl.avif",
        address: "Indore, Madhya Pradesh, India",
        name: "PeopleCrop",
        allTimeEarnings: "7K",
        transactionCompleted: "4",
        employers: "4",
        largestEmployers: "1K",
        memberSince: "Sep 2018",
        typeService: "Business & Finance  >  Human Resources (HR)",
        titleService: "Recruiting & HR Consulting",
        payService: "$21/hr · Starting at $250",
        descriptionService:
          "Hiring best resources for all IT roles, Helping new businesses setting up there HR policies and processes. HR compliances, audits, and payroll. Sourcing, recruiting, lining up candidates, onboarding, For all verticals of IT through different channels like LinkedIn, social networks, local circles, jobboards etc",
        tagSkills: [
          "Benefits Administration",
          "Benefits Design",
          "Compensation Management",
          "Competency Assessment",
          "Consultant",
          "Employee Handbooks",
          "Employee Management",
          "Employment Contracts",
          "Human Resources Management",
          "IT Recruitment",
          "Job Description Writing",
          "Onboarding",
          "Payroll",
          "Process Design",
          "Staffing and Recruiting",
          "Workforce Management",
        ],
      };
    case "13":
      return {
        id: 13,
        imageUrl: "/images/jpv8wttyewfn7lgbjjhk.avif",
        address: "Ajman, Ajman, United Arab Emirates",
        name: "Shweta Kulkarni1",
        allTimeEarnings: "983",
        transactionCompleted: "6",
        employers: "3",
        largestEmployers: "300",
        memberSince: "Sep 2018",
        typeService: "Legal  >  Contracts / Agreements / Policies",
        titleService: "Contracts and claims",
        payService: "$20/hr · Starting at $100",
        descriptionService:
          "Services offering: Contracts management, Contracts drafting, Subcontracts management, preparation & presentation of claims ( Variation, EOT, Cost claims etc.) , contractual letters drafting, disputes, notices, risk analysis, drafting NDA, Supplementary agreement, pre bid agreement, tender analysis, Quantity surveying, BOQ preparation, FIDIC contracts and Training as well.Experience: 14 years of vast experience in the Indian & UAE construction market Area: Construction, service, FM, landscape, power, IT, real estate",
        tagSkills: [
          "Confidentiality Agreement",
          "Construction",
          "Contract Management",
          "Contracts",
          "Corporate Contracts",
          "Drafting",
          "Management",
          "Non Disclosure Agreements (NDA)",
          "Procurement Contracts",
          "Quantity Surveying",
          "Rate Contracts",
          "Real Estate Contracts",
          "Risk Assessment",
          "Sales Contracts",
          "Service Contract",
          "Training",
          "Vendor Contracts",
        ],
      };
    case "14":
      return {
        id: 14,
        imageUrl:
          "/images/BoxLogicSep201915_637097624163401196_guruImgLarge_d85c9113-0e8d-48f7-b3e0-25e47ae48e19.avif",
        address: "Southampton, England, United Kingdom",
        name: "Nishit Nisudan",
        allTimeEarnings: "60K",
        transactionCompleted: "7",
        employers: "7",
        largestEmployers: "10K",
        memberSince: "Nov 2019",
        typeService: "Business & Finance",
        titleService: "Logistics & Warehouse Design /Automation",
        payService: "$170/hr · Starting at $5K",
        descriptionService:
          "Services offering: Contracts management, Contracts drafting, Subcontracts management, preparation & presentation of claims ( Variation, EOT, Cost claims etc.) , contractual letters drafting, disputes, notices, risk analysis, drafting NDA, Supplementary agreement, pre bid agreement, tender analysis, Quantity surveying, BOQ preparation, FIDIC contracts and Training as well.Experience: 14 years of vast experience in the Indian & UAE construction market Area: Construction, service, FM, landscape, power, IT, real estate",
        tagSkills: [
          "Consultant",
          "Design",
          "Ecommerce Consulting",
          "Ecommerce Optimization",
          "Industrial Automation Industry",
          "Logistics",
          "Logistics Consulting",
          "Logistics Design",
          "Logistics Engineering",
          "Management",
          "Strategy",
          "Strategy Development",
          "Supply Chain Consulting",
          "Supply Chain Engineering",
          "Supply Chain Management",
          "Supply Chain Network Planning",
          "Supply Chain Operations",
          "Transportation Engineering",
          "Transportation Software",
          "Warehousing Industry",
        ],
      };
    case "15":
      return {
        id: 15,
        imageUrl:
          "/images/Linkedin Photo_636831174243587906_guruImgLarge_eead0e25-f58d-4e4f-9b7f-1855190e8554.avif",
        address: "Ronkonkoma, NY, USA",
        name: "Jonathan Riker",
        payYear: "150",
        allTimeEarnings: "1,720",
        transactionCompleted: "13",
        employers: "7",
        largestEmployers: "400",
        memberSince: "Oct 2018",
        typeService: "Programming & Development  >  ERP / CRM / SCM",
        titleService: "Supply Chain Management Consulting",
        payService: "$50/hr · Starting at $50",
        descriptionService:
          "I have over 7 years experience as a supply chain professional. I can provide supply chain consulting in this difficult supply chain environment. I can help implement MRP, ERP, planning parameters and much more within your ERP system. I have significant experience implementing MRP within JDE. I also have experience with QAD & SAP. Also, my business intelligence background makes me the perfect candidate to implement inventory management best practices. I can develop Microsoft Excel tools to plan your supply chain. I have implemented successful inventory management programs across multiple manufacturing companies utilizing both Excel tools and MRP solutions. My experience and background with this will help any struggling operation or help you achieve the next level. ",
        tagSkills: [
          "Business Intelligence",
          "Consultant",
          "ERP",
          "Inventory Management",
          "JD Edwards",
          "Management",
          "Management Consulting",
          "Oracle Hyperion",
          "Programming",
          "Software Development",
          "Supply Chain Management",
        ],
      };
  }
};
